# Generated by Django 5.1.4 on 2024-12-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_combo_product_images_product_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
